Source/WebApp/WebApp/Models/SalesReport.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApp.Models;

public class SalesReport
{
    
}

Source/WebApp/WebApp/Controllers/CheckoutController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApp.Data;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CheckoutController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Checkout
        public async Task<IActionResult> Index()
        {
              return _context.Checkout != null ? 
                          View(await _context.Checkout.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Checkout'  is null.");
        }

        // GET: Checkout/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Checkout == null)
            {
                return NotFound();
            }

            var checkout = await _context.Checkout
                .FirstOrDefaultAsync(m => m.CheckoutId == id);
            if (checkout == null)
            {
                return NotFound();
            }

            return View(checkout);
        }

        // GET: Checkout/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Checkout/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CheckoutId,InventoryName,InventoryPic,InventoryPrice")] Checkout checkout)
        {
            if (ModelState.IsValid)
            {
                _context.Add(checkout);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(checkout);
        }

        // GET: Checkout/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Checkout == null)
            {
                return NotFound();
            }

            var checkout = await _context.Checkout.FindAsync(id);
            if (checkout == null)
            {
                return NotFound();
            }
            return View(checkout);
        }

        // POST: Checkout/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CheckoutId,InventoryName,InventoryPic,InventoryPrice")] Checkout checkout)
        {
            if (id != checkout.CheckoutId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(checkout);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CheckoutExists(checkout.CheckoutId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(checkout);
        }

        // GET: Checkout/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Checkout == null)
            {
                return NotFound();
            }

            var checkout = await _context.Checkout
                .FirstOrDefaultAsync(m => m.CheckoutId == id);
            if (checkout == null)
            {
                return NotFound();
            }

            return View(checkout);
        }

        // POST: Checkout/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Checkout == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Checkout'  is null.");
            }
            var checkout = await _context.Checkout.FindAsync(id);
            if (checkout != null)
            {
                _context.Checkout.Remove(checkout);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CheckoutExists(int id)
        {
          return (_context.Checkout?.Any(e => e.CheckoutId == id)).GetValueOrDefault();
        }
    }
}

Source/WebApp/WebApp/Controllers/ConfirmOrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApp.Data;
using WebApp.Models;

namespace WebApp.Controllers;

public class ConfirmOrderController : Controller
{
    private readonly ApplicationDbContext _context;

    public ConfirmOrderController(ApplicationDbContext context)
    {
        _context = context;
    }
    public async Task<IActionResult> Confirm()
    {
        return _context.Inventory != null ?
            View(await _context.Checkout.ToListAsync()) :
            Problem("Entity set 'ApplicationDbContext.Inventory'  is null.");
    }

    public void Create([Bind("SaleId,UserId,Users,InventoryId,Inventorys, SoldDate, StreetName, CityName, StateName, ZipCode,PhoneNumber,CreditCardNumber, ExpirationDate, CVV,ShippingTypeId, Shipping,tax, subtotal, total")] Sales sales){
        if (ModelState.IsValid)
        {
            _context.Add(sales);
            _context.SaveChangesAsync();
        }
    }
}

Source/WebApp/WebApp/Controllers/InventoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using WebApp.Data;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class InventoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ApplicationDbContext _contextCheck;
        
        public InventoryController(ApplicationDbContext context, ApplicationDbContext contextCheck)
        {
            _context = context;
            _contextCheck = contextCheck;
        }

        public List<Inventory> GetInventory()
        {
            List<Inventory> inventory = new List<Inventory>();
            var connectionString = "Data Source=identifier.db";
            
            var contextOptions = new DbContextOptionsBuilder<ApplicationDbContext>()
                .UseSqlite(connectionString).Options;
            
            using var inv = new ApplicationDbContext(contextOptions);
            inventory = inv.Inventory.ToList();
            return inventory;
        }

        public List<Checkout> GetCheckout()
        {
            List<Checkout> checkout = new List<Checkout>();
            var connectionString = "Data Source=identifier.db";
            
            var contextOptions = new DbContextOptionsBuilder<ApplicationDbContext>()
                .UseSqlite(connectionString).Options;
            using var check = new ApplicationDbContext(contextOptions);
            checkout = check.Checkout.ToList();
            
            return checkout;
        }
        public ActionResult Index()
        {
            ViewData["IndexInventory"] = GetInventory();
            ViewData["IndexCheckout"] = GetCheckout();
            return View();
        }
        
        public async Task<IActionResult> IndexInv()
        {
              return _context.Inventory != null ? 
                          View(await _context.Inventory.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Inventory'  is null.");
        }

        // GET: Inventory/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Inventory == null)
            {
                return NotFound();
            }

            var inventory = await _context.Inventory
                .FirstOrDefaultAsync(m => m.InventoryId == id);
            if (inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        // GET: Inventory/ShowItem
        public async Task<IActionResult> ShowItem()
        {
            return _context.Inventory != null ?
                        View() :
                        Problem("Entity set 'ApplicationDbContext.Inventory'  is null.");
        }

        // PoST: Jokes/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            return _context.Inventory != null ?
                        View("Search", await _context.Inventory.Where(i=>i.InventoryName.ToLower().Contains(SearchPhrase.ToLower())).ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Inventory'  is null.");
        }

        // GET: Inventory/Create
        
        public IActionResult Create()
        {
            return View();
        }

        // POST: Inventory/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InventoryId,InventoryName,InventoryDescription,InventoryPic,InventoryPrice")] Inventory inventory)
        {
            if (ModelState.IsValid)
            {
                _context.Add(inventory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(inventory);
        }
        
        // GET: Inventory/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Inventory == null)
            {
                return NotFound();
            }

            var inventory = await _context.Inventory.FindAsync(id);
            if (inventory == null)
            {
                return NotFound();
            }
            return View(inventory);
        }

        public async Task<IActionResult> CreateCartItem(int Id)
        {
            if (ModelState.IsValid)
            {
                if (Id < 0 || _context.Inventory == null)
                {
                    return NotFound();
                }

                var cart = _contextCheck.Checkout;
                var item =await _context.Inventory.FindAsync(Id);
                

                var newItem =new Checkout();
                string? name = item?.InventoryName;
                string? pic = item?.InventoryPic;
                decimal price = item.InventoryPrice;
                if (item != null)
                {
                    newItem = new Checkout(name, pic, price);
                }

                
                var listForLoop = _contextCheck.Checkout.ToList();
                
                var num = 0;
                for (int i = 0; i < listForLoop.Count; i++)
                {
                    if ((listForLoop[i].InventoryName.Equals(newItem.InventoryName)))
                    {
                        num++;
                        break;
                    }
                }
                if (num == 0)
                {
                    _contextCheck.Add(newItem);
                }

                num = 0;
                await _contextCheck.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }
        
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InventoryId,InventoryName,InventoryDescription,InventoryPic,InventoryPrice")] Inventory inventory)
        {
            if (id != inventory.InventoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(inventory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InventoryExists(inventory.InventoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(inventory);
        }

        // GET: Inventory/Delete/5
        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Inventory == null)
            {
                return NotFound();
            }

            var inventory = await _context.Inventory
                .FirstOrDefaultAsync(m => m.InventoryId == id);
            if (inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        // POST: Inventory/Delete/5
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Inventory == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Inventory'  is null.");
            }
            var inventory = await _context.Inventory.FindAsync(id);
            if (inventory != null)
            {
                _context.Inventory.Remove(inventory);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InventoryExists(int id)
        {
          return (_context.Inventory?.Any(e => e.InventoryId == id)).GetValueOrDefault();
        }
    }
}

Source/WebApp/WebApp/Controllers/OrderCompleteController.cs
using Microsoft.AspNetCore.Mvc;

namespace LootXApp.Controllers;

public class OrderCompleteController : Controller
{
    public IActionResult Complete()
    {
        return View();
    }
}

Source/WebApp/WebApp/Views/Shared/AddInventory.cshtml
@page
@model WebApp.Views.Shared.Add_Inventory
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html lang="en">
<head>
    <title> Add Products to Inventory </title>
    <h1> Add Products to Inventory </h1>
</head>
<body>

<fieldset class="border-white">
    <form method="post" asp-action="">
        <div class="form-group">
            <label class="col-form-label col-form-label-lg mt-4" for="inputLarge">Product Name</label>
            <input class="form-control form-control-lg" type="text" placeholder="Product Name" id="inputLarge">
        </div>
     
        <label class="col-form-label col-form-label-lg mt-4" for="inputLarge">Product Price</label>
        <div class="input-group mb-3">
            <span class="input-group-text">$</span>
            <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)">
        </div>
     
        <div class="form-group">
            <label class="col-form-label col-form-label-lg mt-4" for="inputLarge">Product Description</label>
            <textarea class="form-control" id="exampleTextarea" rows="3" spellcheck="false" placeholder="Description"></textarea>
        </div>
     
        <div class="form-group">
            <label class="col-form-label col-form-label-lg mt-4" for="inputLarge">Upload Product Image</label>
            <input class="form-control" type="file" id="formFile">
        </div>
        <br/>
        <button type="submit" class="btn btn-outline-success">Add Product</button>   
     
    </form>
    
</fieldset>

</body>
</html>

Source/WebApp/WebApp/Views/Shared/Cart.cshtml
@page
@model WebApp.Views.Shared.Cart

@{
  Layout = "_Layout";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="~/css/myTheme.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true"/>
</head>

<body>
<div>
</div>
</body>
</html>

Source/WebApp/WebApp/Views/Shared/SalesReport.cshtml
@page
@model WebApp.Views.Shared.SalesReport

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Item</th>
      <th scope="col">Purchased By</th>
      <th scope="col">Purchased On</th>
      <th scope="col">Order Total</th>
    </tr>
  </thead>
  <tbody>
    <tr class="table-active">
      <th scope="row">Active</th>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr>
      <th scope="row">Default</th>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr class="table-primary">
      <th scope="row">Primary</th>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr class="table-secondary">
      <th scope="row">Secondary</th>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr class="table-success">
      <th scope="row">Success</th>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr class="table-danger">
      <th scope="row">Danger</th>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr class="table-warning">
      <th scope="row">Warning</th>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr class="table-info">
      <th scope="row">Info</th>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr class="table-light">
      <th scope="row">Light</th>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr class="table-dark">
      <th scope="row">Dark</th>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
  </tbody>
</table>
</body>
</html>

Source/WebApp/WebApp/Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Users> SignInManager
@inject UserManager<Users> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - LootX</title>
    <link rel="stylesheet" href="~/css/myTheme.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a asp-area="" asp-controller="Inventory" asp-action="Index" style= "margin-right: auto; "><img src="/Images/Icons/LootX Logo 3D.png" class="logo" alt="LootX Logo" style="width: 50px"></a>
            <div class="collapse navbar-collapse" id="navbarColor03">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Inventory" asp-action="Index">Home</a>
                    </li>
                    
                    @* Test for shipping *@
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="ShippingPayment" asp-action="Shipping">Shipping</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="ConfirmOrder" asp-action="Confirm">Confirm</a>
                    </li>
                    
                    
                    
                    <li class="nav-item">
                                            <a class="nav-link" asp-area="" asp-controller="OrderComplete" asp-action="Complete">Complete</a>
                                            </li>
                    
                    
                    @if (User.IsInRole("Admin"))
                 {
                     <li class="nav-item">
                         <a asp-controller="Inventory" asp-action="IndexInv" class="nav-link" >Add Inventory</a>
                     </li>
                     <li class="nav-item">
                         <a class="nav-link" asp-area="" asp-controller="Home" asp-action="SalesReport">Sales Report</a>
                         </li>
                 }   
                </ul>
                
                
                <form asp-controller = "Inventory" asp-action = "ShowSearchResults" class="d-flex">
                    <input name="SearchPhrase" class="form-control me-sm-2" type="search" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>
                
                @section Scripts {
                    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
                }
                
                <partial name="_LoginPartial"/>
                
                <a class="nav-item nav-link text-dark" id="myCart" asp-controller="Checkout" asp-action="Index"> <img src="/Images/Icons/basket-cart-icon-27.png" class="cart" alt="Cart Icon" style="width: 50px"/> 
                    My Cart
                    </a>
                
                
            </div>
        </div>
        

    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - LootX - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
</html>